export const countries = [
    { name: "Afghanistan", code: "AF", dial_code: "+93" },
    { name: "Australia", code: "AU", dial_code: "+61" },
    { name: "Bahrain", code: "BH", dial_code: "+973" },
    { name: "Bangladesh", code: "BD", dial_code: "+880" },
    { name: "Canada", code: "CA", dial_code: "+1" },
    { name: "China", code: "CN", dial_code: "+86" },
    { name: "Germany", code: "DE", dial_code: "+49" },
    { name: "India", code: "IN", dial_code: "+91" },
    { name: "Indonesia", code: "ID", dial_code: "+62" },
    { name: "Iran", code: "IR", dial_code: "+98" },
    { name: "Iraq", code: "IQ", dial_code: "+964" },
    { name: "Kuwait", code: "KW", dial_code: "+965" },
    { name: "Malaysia", code: "MY", dial_code: "+60" },
    { name: "Oman", code: "OM", dial_code: "+968" },
    { name: "Pakistan", code: "PK", dial_code: "+92" },
    { name: "Qatar", code: "QA", dial_code: "+974" },
    { name: "Saudi Arabia", code: "SA", dial_code: "+966" },
    { name: "Singapore", code: "SG", dial_code: "+65" },
    { name: "Sri Lanka", code: "LK", dial_code: "+94" },
    { name: "Turkey", code: "TR", dial_code: "+90" },
    { name: "United Arab Emirates", code: "AE", dial_code: "+971" },
    { name: "United Kingdom", code: "GB", dial_code: "+44" },
    { name: "United States", code: "US", dial_code: "+1" },
    { name: "Yemen", code: "YE", dial_code: "+967" },
].sort((a, b) => a.name.localeCompare(b.name));
